language: minimal

services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.28.5

before_install:
  # Docker Compose Install 
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
# Pre-testing installs
install:
  - docker build --platform=linux/amd64 udagram-api-user-2:latest
  - docker build --platform=linux/amd64 udagram-api-feed-2:latest
  - docker build --platform=linux/amd64 udagram-frontend-2:latest
  - docker build --platform=linux/amd64 reverseproxy-2:latest
  - docker tag udagram-api-feed germanho112/udagram-api-feed:latest
  - docker tag udagram-api-user germanho112/udagram-api-user:latest
  - docker tag udagram-frontend:local germanho112/udagram-frontend:latest
  - docker tag reverseproxy germanho112/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-api-user:latest
  - docker push "$DOCKER_USERNAME"/udagram-api-feed:latest
  - docker push "$DOCKER_USERNAME"/udagram-frontend:local
  - docker push "$DOCKER_USERNAME"/reverseproxy:latest